import "@/src/app/styles/globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

export const metadata = {
  title: "Page Builder",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="">
        <Header />
        <div className="flex h-full w-full flex-col items-center bg-black">
          {children}
        </div>
        <Footer />
        {draftMode().isEnabled && (
          <a
            className="fixed bottom-0 right-0 m-4 bg-blue-500 p-4 text-white"
            href="/api/draft-mode/disable"
          >
            Disable preview mode
          </a>
        )}
        {draftMode().isEnabled && <VisualEditing />}
      </body>
    </html>
  );
}
