import { Inter } from "next/font/google";
import "@/src/app/styles/globals.css";
import Footer from "@/components/layout/Footer";
import { sanityFetch } from "@/src/sanity/lib/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Page Builder",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const page = await sanityFetch({ query: PAGE_BUILDER_QUERY });
  return (
    <html lang="en">
      <body>
        <div className="flex h-full w-full flex-col items-center bg-black">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
