import "@/src/app/styles/globals.css";
import Footer from "@/components/layout/Footer";
import { sanityFetch } from "@/src/sanity/lib/client";
import { GLOBAL_SETTINGS_QUERY } from "@/src/lib/sanity/queries";

export const metadata = {
  title: "Page Builder",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await sanityFetch({ query: GLOBAL_SETTINGS_QUERY });
  return (
    <html lang="en">
      <body>
        <div className="flex h-full w-full flex-col items-center bg-black">
          {children}
        </div>
        <Footer data={data} />
      </body>
    </html>
  );
}
